from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


RUNNER_VERSION = "v2"
RUN_REGISTRY = Path("results/run_registry.json")
PERSISTENCE_DIAGNOSTIC_TASK = "__runner_persistence_diagnostic__"
EXP002_SCIENTIFIC_FREEZE_PATHS = (
    "artificial_agency/experiments/exp002",
    "experiments/002-fixed-conflict-pressure",
    "tests/experiments/exp002",
    "pyproject.toml",
)
EXP003_SCIENTIFIC_FREEZE_PATHS = (
    "artificial_agency/experiments/exp003",
    "experiments/003-constraint-status-pressure",
    "tests/experiments/exp003",
    "pyproject.toml",
)
EXP004_SCIENTIFIC_FREEZE_PATHS = (
    "artificial_agency/_registry.py",
    "artificial_agency/experiments/exp004",
    "experiments/004-constraint-meaning-validation",
    "tests/experiments/exp004",
    "pyproject.toml",
)
EXP005_REFERENCE_FREEZE_PATHS = (
    "artificial_agency/experiments/exp004",
    "experiments/004-constraint-meaning-validation",
)
EXP006_SCIENTIFIC_FREEZE_PATHS = (
    "artificial_agency/experiments/exp006",
    "experiments/006-action-representational-compliance",
    "tests/experiments/exp006",
    "pyproject.toml",
)
EXP007_SCIENTIFIC_FREEZE_PATHS = (
    "artificial_agency/_registry.py",
    "artificial_agency/experiments/exp007",
    "experiments/007-scenario-suite-pilot",
    "tests/experiments/exp007",
    "pyproject.toml",
)
EXP008_SCIENTIFIC_FREEZE_PATHS = (
    "artificial_agency/_registry.py",
    "artificial_agency/experiments/exp008",
    "artificial_agency/runner/exp008_recovery_task.py",
    "experiments/008-evaluation-awareness",
    "tests/experiments/exp008",
    "pyproject.toml",
)
EXP008B_SCIENTIFIC_FREEZE_PATHS = (
    "artificial_agency/experiments/exp008b",
    "experiments/008b-evaluation-awareness",
    "tests/experiments/exp008b",
    "pyproject.toml",
)


@dataclass(frozen=True)
class RunSpec:
    run_id: str
    experiment_id: str
    title: str
    frozen_commit: str
    scientific_paths: tuple[str, ...]
    task: str
    model: str
    total_samples: int
    condition_counts: dict[str, int]
    log_dir: Path
    status_path: Path
    operational_log: Path
    lock_path: Path
    pid_path: Path
    stdout_path: Path
    canary_log_dir: Path
    previous_attempts: list[dict[str, str]] = field(default_factory=list)
    inspect_args: tuple[str, ...] = ()
    recovery_batch_size: int | None = None


def repository_root() -> Path:
    return Path(__file__).resolve().parents[2]


def runtime_home(root: Path, run_id: str) -> Path:
    return root / "results" / ".runner-runtime" / run_id


def known_runs(root: Path | None = None) -> dict[str, RunSpec]:
    repo = root or repository_root()
    run002_root = repo / "results" / "002-fixed-conflict-pressure" / "run-002A"
    run003_root = repo / "results" / "003-constraint-status-pressure" / "run-003A"
    run004a_root = repo / "results" / "004-constraint-meaning-validation" / "run-004A"
    run004b_root = repo / "results" / "004-constraint-meaning-validation" / "run-004B"
    run005b_root = repo / "results" / "005-cross-model-replication" / "run-005B"
    run005c_root = repo / "results" / "005-cross-model-replication" / "run-005C"
    run006a_root = repo / "results" / "006-action-representational-compliance" / "run-006A-GPT"
    run006b_root = repo / "results" / "006-action-representational-compliance" / "run-006B-CLAUDE"
    run006c_root = repo / "results" / "006-action-representational-compliance" / "run-006C-GEMINI"
    run007a_root = repo / "results" / "007-scenario-suite-pilot" / "run-007A-GPT"
    run007b_root = repo / "results" / "007-scenario-suite-pilot" / "run-007B-CLAUDE"
    run007c_root = repo / "results" / "007-scenario-suite-pilot" / "run-007C-GEMINI"
    run008a_root = repo / "results" / "008-evaluation-awareness" / "run-008A-GPT"
    run008b_root = repo / "results" / "008-evaluation-awareness" / "run-008B-CLAUDE"
    run008c_root = repo / "results" / "008-evaluation-awareness" / "run-008C-GEMINI"
    run008ba_root = repo / "results" / "008b-evaluation-awareness" / "run-008B-A-GPT"
    run008bb_root = repo / "results" / "008b-evaluation-awareness" / "run-008B-B-CLAUDE"
    run008bc_root = repo / "results" / "008b-evaluation-awareness" / "run-008B-C-GEMINI"
    exp006_counts = {
        "categorical-ordinary": 30,
        "categorical-high": 30,
        "procedural-ordinary": 30,
        "procedural-high": 30,
        "explicit-purpose-conflict-ordinary": 30,
        "explicit-purpose-conflict-high": 30,
    }
    exp006_frozen_commit = "aeab4f447cdb57f2f1db3c5a7ca61a09266a0df8"
    exp007_counts = {
        "refund": 30,
        "procurement": 30,
        "data-access": 30,
        "scheduling": 30,
    }
    exp007_frozen_commit = "8881ef8375493ac82d8ccc5fa4cb47a8a54857c8"
    exp008_counts = {
        "procurement-eval-salient": 30,
        "procurement-naturalistic": 30,
        "data-access-eval-salient": 30,
        "data-access-naturalistic": 30,
    }
    exp008_frozen_commit = "02f7098dea80156ae48faee5ee091659f538beee"
    exp008b_counts = exp008_counts
    exp008b_frozen_commit = "d9cfe9603b3de9591e015c72506bdab38d07b4db"
    return {
        "002A": RunSpec(
            run_id="002A",
            experiment_id="002-fixed-conflict-pressure",
            title="Experiment 002 Run 002A",
            frozen_commit="6301fc0b78ded0200fd6203d4888ac2b3c33cae7",
            scientific_paths=EXP002_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp002/"
                "inspect_task.py@exp002_fixed_conflict_phase1"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=90,
            condition_counts={"low": 30, "medium": 30, "high": 30},
            log_dir=run002_root / "inspect",
            status_path=run002_root / "RUN_STATUS.json",
            operational_log=run002_root / "operational.log",
            lock_path=run002_root / "RUN_LOCK.json",
            pid_path=run002_root / "RUNNER.pid",
            stdout_path=run002_root / "runner-supervisor.out",
            canary_log_dir=run002_root / "canary",
            previous_attempts=[
                {
                    "kind": "technical_pre_result_failure",
                    "completed": "0",
                    "reason": "DNS/API connectivity failure before completed samples",
                    "raw_log_sha256": (
                        "b18f043830d2d4e6ca791a119d3b6512afa6979c0bef089e22968fa0dac1dbdf"
                    ),
                }
            ],
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp002,phase1,run002A,fixed-conflict-pressure",
                "--metadata",
                "experiment_id=002-fixed-conflict-pressure",
                "--metadata",
                "phase=fixed_conflict_pressure",
                "--metadata",
                "run_id=run-002A",
                "--metadata",
                "git_commit=6301fc0b78ded0200fd6203d4888ac2b3c33cae7",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "003A": RunSpec(
            run_id="003A",
            experiment_id="003-constraint-status-pressure",
            title="Experiment 003 Run 003A Stage 1",
            frozen_commit="f8294ab172cb556f8a4c1ec4f726947672cc859a",
            scientific_paths=EXP003_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp003/"
                "inspect_task.py@exp003_constraint_status_stage1"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=120,
            condition_counts={
                "categorical-ordinary": 20,
                "categorical-high": 20,
                "procedural-ordinary": 20,
                "procedural-high": 20,
                "purpose-conflict-ordinary": 20,
                "purpose-conflict-high": 20,
            },
            log_dir=run003_root / "inspect",
            status_path=run003_root / "RUN_STATUS.json",
            operational_log=run003_root / "operational.log",
            lock_path=run003_root / "RUN_LOCK.json",
            pid_path=run003_root / "RUNNER.pid",
            stdout_path=run003_root / "runner-supervisor.out",
            canary_log_dir=run003_root / "canary",
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp003,stage1,run003A,constraint-status-pressure",
                "--metadata",
                "experiment_id=003-constraint-status-pressure",
                "--metadata",
                "phase=constraint_status_pressure_stage1",
                "--metadata",
                "run_id=run-003A",
                "--metadata",
                "git_commit=f8294ab172cb556f8a4c1ec4f726947672cc859a",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "003B": RunSpec(
            run_id="003B",
            experiment_id="003-constraint-status-pressure",
            title="Experiment 003 Run 003B Stage 2",
            frozen_commit="f8294ab172cb556f8a4c1ec4f726947672cc859a",
            scientific_paths=EXP003_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/runner/"
                "exp003_stage2_task.py@exp003_constraint_status_stage2"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=180,
            condition_counts={
                "categorical-ordinary": 30,
                "categorical-high": 30,
                "procedural-ordinary": 30,
                "procedural-high": 30,
                "purpose-conflict-ordinary": 30,
                "purpose-conflict-high": 30,
            },
            log_dir=repo
            / "results"
            / "003-constraint-status-pressure"
            / "run-003B"
            / "inspect",
            status_path=repo
            / "results"
            / "003-constraint-status-pressure"
            / "run-003B"
            / "RUN_STATUS.json",
            operational_log=repo
            / "results"
            / "003-constraint-status-pressure"
            / "run-003B"
            / "operational.log",
            lock_path=repo
            / "results"
            / "003-constraint-status-pressure"
            / "run-003B"
            / "RUN_LOCK.json",
            pid_path=repo
            / "results"
            / "003-constraint-status-pressure"
            / "run-003B"
            / "RUNNER.pid",
            stdout_path=repo
            / "results"
            / "003-constraint-status-pressure"
            / "run-003B"
            / "runner-supervisor.out",
            canary_log_dir=repo
            / "results"
            / "003-constraint-status-pressure"
            / "run-003B"
            / "canary",
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp003,stage2,run003B,constraint-status-pressure",
                "--metadata",
                "experiment_id=003-constraint-status-pressure",
                "--metadata",
                "phase=constraint_status_pressure_stage2",
                "--metadata",
                "run_id=run-003B",
                "--metadata",
                "git_commit=f8294ab172cb556f8a4c1ec4f726947672cc859a",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "004A": RunSpec(
            run_id="004A",
            experiment_id="004-constraint-meaning-validation",
            title="Experiment 004 Run 004A Stage 1",
            frozen_commit="aa126f9254a01c96e85545a9e1a77d10195f2604",
            scientific_paths=EXP004_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp004/"
                "inspect_task.py@exp004_constraint_meaning_stage1"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=120,
            condition_counts={
                "categorical-ordinary": 20,
                "categorical-high": 20,
                "procedural-ordinary": 20,
                "procedural-high": 20,
                "explicit-purpose-conflict-ordinary": 20,
                "explicit-purpose-conflict-high": 20,
            },
            log_dir=run004a_root / "inspect",
            status_path=run004a_root / "RUN_STATUS.json",
            operational_log=run004a_root / "operational.log",
            lock_path=run004a_root / "RUN_LOCK.json",
            pid_path=run004a_root / "RUNNER.pid",
            stdout_path=run004a_root / "runner-supervisor.out",
            canary_log_dir=run004a_root / "canary",
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp004,stage1,run004A,constraint-meaning-validation",
                "--metadata",
                "experiment_id=004-constraint-meaning-validation",
                "--metadata",
                "phase=constraint_meaning_validation_stage1",
                "--metadata",
                "run_id=run-004A",
                "--metadata",
                "git_commit=aa126f9254a01c96e85545a9e1a77d10195f2604",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "004B": RunSpec(
            run_id="004B",
            experiment_id="004-constraint-meaning-validation",
            title="Experiment 004 Run 004B Stage 2",
            frozen_commit="aa126f9254a01c96e85545a9e1a77d10195f2604",
            scientific_paths=EXP004_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/runner/"
                "exp004_stage2_task.py@exp004_constraint_meaning_stage2"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=180,
            condition_counts={
                "categorical-ordinary": 30,
                "categorical-high": 30,
                "procedural-ordinary": 30,
                "procedural-high": 30,
                "explicit-purpose-conflict-ordinary": 30,
                "explicit-purpose-conflict-high": 30,
            },
            log_dir=run004b_root / "inspect",
            status_path=run004b_root / "RUN_STATUS.json",
            operational_log=run004b_root / "operational.log",
            lock_path=run004b_root / "RUN_LOCK.json",
            pid_path=run004b_root / "RUNNER.pid",
            stdout_path=run004b_root / "runner-supervisor.out",
            canary_log_dir=run004b_root / "canary",
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp004,stage2,run004B,constraint-meaning-validation",
                "--metadata",
                "experiment_id=004-constraint-meaning-validation",
                "--metadata",
                "phase=constraint_meaning_validation_stage2",
                "--metadata",
                "run_id=run-004B",
                "--metadata",
                "git_commit=aa126f9254a01c96e85545a9e1a77d10195f2604",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "005B": RunSpec(
            run_id="005B",
            experiment_id="005-cross-model-replication",
            title="Experiment 005 Run 005B Claude Sonnet 5",
            frozen_commit="aa126f9254a01c96e85545a9e1a77d10195f2604",
            scientific_paths=EXP005_REFERENCE_FREEZE_PATHS,
            task=(
                "artificial_agency/runner/"
                "exp005_cross_model_task.py@exp005_model_b_claude_sonnet5"
            ),
            model="anthropic/claude-sonnet-5",
            total_samples=300,
            condition_counts={
                "categorical-ordinary": 50,
                "categorical-high": 50,
                "procedural-ordinary": 50,
                "procedural-high": 50,
                "explicit-purpose-conflict-ordinary": 50,
                "explicit-purpose-conflict-high": 50,
            },
            log_dir=run005b_root / "inspect",
            status_path=run005b_root / "RUN_STATUS.json",
            operational_log=run005b_root / "operational.log",
            lock_path=run005b_root / "RUN_LOCK.json",
            pid_path=run005b_root / "RUNNER.pid",
            stdout_path=run005b_root / "runner-supervisor.out",
            canary_log_dir=run005b_root / "canary",
            inspect_args=(
                "--model",
                "anthropic/claude-sonnet-5",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp005,model-b,run005B,cross-model-replication",
                "--metadata",
                "experiment_id=005-cross-model-replication",
                "--metadata",
                "phase=cross_model_replication_full",
                "--metadata",
                "run_id=run-005B",
                "--metadata",
                "model_role=model_b",
                "--metadata",
                "reference_scientific_sha=aa126f9254a01c96e85545a9e1a77d10195f2604",
                "--metadata",
                "preregistration_sha=20aa46df84964b5ab55354a063b8ebe3f57e26c0",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "005C": RunSpec(
            run_id="005C",
            experiment_id="005-cross-model-replication",
            title="Experiment 005 Run 005C Gemini 3.7 Flash",
            frozen_commit="aa126f9254a01c96e85545a9e1a77d10195f2604",
            scientific_paths=EXP005_REFERENCE_FREEZE_PATHS,
            task=(
                "artificial_agency/runner/"
                "exp005_cross_model_task.py@exp005_model_c_gemini37_flash"
            ),
            model="google/gemini-3.7-flash",
            total_samples=300,
            condition_counts={
                "categorical-ordinary": 50,
                "categorical-high": 50,
                "procedural-ordinary": 50,
                "procedural-high": 50,
                "explicit-purpose-conflict-ordinary": 50,
                "explicit-purpose-conflict-high": 50,
            },
            log_dir=run005c_root / "inspect",
            status_path=run005c_root / "RUN_STATUS.json",
            operational_log=run005c_root / "operational.log",
            lock_path=run005c_root / "RUN_LOCK.json",
            pid_path=run005c_root / "RUNNER.pid",
            stdout_path=run005c_root / "runner-supervisor.out",
            canary_log_dir=run005c_root / "canary",
            inspect_args=(
                "--model",
                "google/gemini-3.7-flash",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp005,model-c,run005C,cross-model-replication",
                "--metadata",
                "experiment_id=005-cross-model-replication",
                "--metadata",
                "phase=cross_model_replication_full",
                "--metadata",
                "run_id=run-005C",
                "--metadata",
                "model_role=model_c",
                "--metadata",
                "reference_scientific_sha=aa126f9254a01c96e85545a9e1a77d10195f2604",
                "--metadata",
                "preregistration_sha=20aa46df84964b5ab55354a063b8ebe3f57e26c0",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "006A-GPT": RunSpec(
            run_id="006A-GPT",
            experiment_id="006-action-representational-compliance",
            title="Experiment 006 Run 006A GPT-5.6 Sol",
            frozen_commit=exp006_frozen_commit,
            scientific_paths=EXP006_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp006/"
                "inspect_task.py@exp006_model_a_gpt56_sol"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=180,
            condition_counts=exp006_counts,
            log_dir=run006a_root / "inspect",
            status_path=run006a_root / "RUN_STATUS.json",
            operational_log=run006a_root / "operational.log",
            lock_path=run006a_root / "RUN_LOCK.json",
            pid_path=run006a_root / "RUNNER.pid",
            stdout_path=run006a_root / "runner-supervisor.out",
            canary_log_dir=run006a_root / "canary",
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp006,model-a,run006A-GPT,action-representation",
                "--metadata",
                "experiment_id=006-action-representational-compliance",
                "--metadata",
                "phase=action_representational_compliance",
                "--metadata",
                "run_id=run-006A-GPT",
                "--metadata",
                "model_role=model_a_gpt",
                "--metadata",
                "preregistration_sha=f50b1313be0757ef0cdb034f1f8ea6df29cef79c",
                "--metadata",
                f"git_commit={exp006_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "006B-CLAUDE": RunSpec(
            run_id="006B-CLAUDE",
            experiment_id="006-action-representational-compliance",
            title="Experiment 006 Run 006B Claude Sonnet 5",
            frozen_commit=exp006_frozen_commit,
            scientific_paths=EXP006_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp006/"
                "inspect_task.py@exp006_model_b_claude_sonnet5"
            ),
            model="anthropic/claude-sonnet-5",
            total_samples=180,
            condition_counts=exp006_counts,
            log_dir=run006b_root / "inspect",
            status_path=run006b_root / "RUN_STATUS.json",
            operational_log=run006b_root / "operational.log",
            lock_path=run006b_root / "RUN_LOCK.json",
            pid_path=run006b_root / "RUNNER.pid",
            stdout_path=run006b_root / "runner-supervisor.out",
            canary_log_dir=run006b_root / "canary",
            inspect_args=(
                "--model",
                "anthropic/claude-sonnet-5",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp006,model-b,run006B-CLAUDE,action-representation",
                "--metadata",
                "experiment_id=006-action-representational-compliance",
                "--metadata",
                "phase=action_representational_compliance",
                "--metadata",
                "run_id=run-006B-CLAUDE",
                "--metadata",
                "model_role=model_b_claude",
                "--metadata",
                "preregistration_sha=f50b1313be0757ef0cdb034f1f8ea6df29cef79c",
                "--metadata",
                f"git_commit={exp006_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "006C-GEMINI": RunSpec(
            run_id="006C-GEMINI",
            experiment_id="006-action-representational-compliance",
            title="Experiment 006 Run 006C Gemini 3.7 Flash",
            frozen_commit=exp006_frozen_commit,
            scientific_paths=EXP006_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp006/"
                "inspect_task.py@exp006_model_c_gemini37_flash"
            ),
            model="google/gemini-3.7-flash",
            total_samples=180,
            condition_counts=exp006_counts,
            log_dir=run006c_root / "inspect",
            status_path=run006c_root / "RUN_STATUS.json",
            operational_log=run006c_root / "operational.log",
            lock_path=run006c_root / "RUN_LOCK.json",
            pid_path=run006c_root / "RUNNER.pid",
            stdout_path=run006c_root / "runner-supervisor.out",
            canary_log_dir=run006c_root / "canary",
            inspect_args=(
                "--model",
                "google/gemini-3.7-flash",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp006,model-c,run006C-GEMINI,action-representation",
                "--metadata",
                "experiment_id=006-action-representational-compliance",
                "--metadata",
                "phase=action_representational_compliance",
                "--metadata",
                "run_id=run-006C-GEMINI",
                "--metadata",
                "model_role=model_c_gemini",
                "--metadata",
                "preregistration_sha=f50b1313be0757ef0cdb034f1f8ea6df29cef79c",
                "--metadata",
                f"git_commit={exp006_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "007A-GPT": RunSpec(
            run_id="007A-GPT",
            experiment_id="007-scenario-suite-pilot",
            title="Experiment 007 Run 007A GPT-5.6 Sol",
            frozen_commit=exp007_frozen_commit,
            scientific_paths=EXP007_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp007/"
                "inspect_task.py@exp007_model_a_gpt56_sol"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=120,
            condition_counts=exp007_counts,
            log_dir=run007a_root / "inspect",
            status_path=run007a_root / "RUN_STATUS.json",
            operational_log=run007a_root / "operational.log",
            lock_path=run007a_root / "RUN_LOCK.json",
            pid_path=run007a_root / "RUNNER.pid",
            stdout_path=run007a_root / "runner-supervisor.out",
            canary_log_dir=run007a_root / "canary",
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp007,model-a,run007A-GPT,scenario-suite-pilot",
                "--metadata",
                "experiment_id=007-scenario-suite-pilot",
                "--metadata",
                "phase=scenario_suite_pilot",
                "--metadata",
                "run_id=run-007A-GPT",
                "--metadata",
                "model_role=model_a_gpt",
                "--metadata",
                "preregistration_sha=0ae3e52ca42b451cc5f5fdb01214916aaf58e0c0",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp007_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "007B-CLAUDE": RunSpec(
            run_id="007B-CLAUDE",
            experiment_id="007-scenario-suite-pilot",
            title="Experiment 007 Run 007B Claude Sonnet 5",
            frozen_commit=exp007_frozen_commit,
            scientific_paths=EXP007_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp007/"
                "inspect_task.py@exp007_model_b_claude_sonnet5"
            ),
            model="anthropic/claude-sonnet-5",
            total_samples=120,
            condition_counts=exp007_counts,
            log_dir=run007b_root / "inspect",
            status_path=run007b_root / "RUN_STATUS.json",
            operational_log=run007b_root / "operational.log",
            lock_path=run007b_root / "RUN_LOCK.json",
            pid_path=run007b_root / "RUNNER.pid",
            stdout_path=run007b_root / "runner-supervisor.out",
            canary_log_dir=run007b_root / "canary",
            inspect_args=(
                "--model",
                "anthropic/claude-sonnet-5",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp007,model-b,run007B-CLAUDE,scenario-suite-pilot",
                "--metadata",
                "experiment_id=007-scenario-suite-pilot",
                "--metadata",
                "phase=scenario_suite_pilot",
                "--metadata",
                "run_id=run-007B-CLAUDE",
                "--metadata",
                "model_role=model_b_claude",
                "--metadata",
                "preregistration_sha=0ae3e52ca42b451cc5f5fdb01214916aaf58e0c0",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp007_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "007C-GEMINI": RunSpec(
            run_id="007C-GEMINI",
            experiment_id="007-scenario-suite-pilot",
            title="Experiment 007 Run 007C Gemini 3.7 Flash",
            frozen_commit=exp007_frozen_commit,
            scientific_paths=EXP007_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp007/"
                "inspect_task.py@exp007_model_c_gemini37_flash"
            ),
            model="google/gemini-3.7-flash",
            total_samples=120,
            condition_counts=exp007_counts,
            log_dir=run007c_root / "inspect",
            status_path=run007c_root / "RUN_STATUS.json",
            operational_log=run007c_root / "operational.log",
            lock_path=run007c_root / "RUN_LOCK.json",
            pid_path=run007c_root / "RUNNER.pid",
            stdout_path=run007c_root / "runner-supervisor.out",
            canary_log_dir=run007c_root / "canary",
            inspect_args=(
                "--model",
                "google/gemini-3.7-flash",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp007,model-c,run007C-GEMINI,scenario-suite-pilot",
                "--metadata",
                "experiment_id=007-scenario-suite-pilot",
                "--metadata",
                "phase=scenario_suite_pilot",
                "--metadata",
                "run_id=run-007C-GEMINI",
                "--metadata",
                "model_role=model_c_gemini",
                "--metadata",
                "preregistration_sha=0ae3e52ca42b451cc5f5fdb01214916aaf58e0c0",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp007_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "008A-GPT": RunSpec(
            run_id="008A-GPT",
            experiment_id="008-evaluation-awareness",
            title="Experiment 008 Run 008A GPT-5.6 Sol",
            frozen_commit=exp008_frozen_commit,
            scientific_paths=EXP008_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp008/"
                "inspect_task.py@exp008_model_a_gpt56_sol"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=120,
            condition_counts=exp008_counts,
            log_dir=run008a_root / "inspect",
            status_path=run008a_root / "RUN_STATUS.json",
            operational_log=run008a_root / "operational.log",
            lock_path=run008a_root / "RUN_LOCK.json",
            pid_path=run008a_root / "RUNNER.pid",
            stdout_path=run008a_root / "runner-supervisor.out",
            canary_log_dir=run008a_root / "canary",
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp008,model-a,run008A-GPT,evaluation-awareness",
                "--metadata",
                "experiment_id=008-evaluation-awareness",
                "--metadata",
                "phase=evaluation_awareness_naturalistic_embedding",
                "--metadata",
                "run_id=run-008A-GPT",
                "--metadata",
                "model_role=model_a_gpt",
                "--metadata",
                "preregistration_sha=0aa5935f6830afe3e9f447ca9c299420e0a39586",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp008_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "008B-CLAUDE": RunSpec(
            run_id="008B-CLAUDE",
            experiment_id="008-evaluation-awareness",
            title="Experiment 008 Run 008B Claude Sonnet 5",
            frozen_commit=exp008_frozen_commit,
            scientific_paths=EXP008_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp008/"
                "inspect_task.py@exp008_model_b_claude_sonnet5"
            ),
            model="anthropic/claude-sonnet-5",
            total_samples=120,
            condition_counts=exp008_counts,
            log_dir=run008b_root / "inspect",
            status_path=run008b_root / "RUN_STATUS.json",
            operational_log=run008b_root / "operational.log",
            lock_path=run008b_root / "RUN_LOCK.json",
            pid_path=run008b_root / "RUNNER.pid",
            stdout_path=run008b_root / "runner-supervisor.out",
            canary_log_dir=run008b_root / "canary",
            inspect_args=(
                "--model",
                "anthropic/claude-sonnet-5",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp008,model-b,run008B-CLAUDE,evaluation-awareness",
                "--metadata",
                "experiment_id=008-evaluation-awareness",
                "--metadata",
                "phase=evaluation_awareness_naturalistic_embedding",
                "--metadata",
                "run_id=run-008B-CLAUDE",
                "--metadata",
                "model_role=model_b_claude",
                "--metadata",
                "preregistration_sha=0aa5935f6830afe3e9f447ca9c299420e0a39586",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp008_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "008C-GEMINI": RunSpec(
            run_id="008C-GEMINI",
            experiment_id="008-evaluation-awareness",
            title="Experiment 008 Run 008C Gemini 3.7 Flash",
            frozen_commit=exp008_frozen_commit,
            scientific_paths=EXP008_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp008/"
                "inspect_task.py@exp008_model_c_gemini37_flash"
            ),
            model="google/gemini-3.7-flash",
            total_samples=120,
            condition_counts=exp008_counts,
            log_dir=run008c_root / "inspect",
            status_path=run008c_root / "RUN_STATUS.json",
            operational_log=run008c_root / "operational.log",
            lock_path=run008c_root / "RUN_LOCK.json",
            pid_path=run008c_root / "RUNNER.pid",
            stdout_path=run008c_root / "runner-supervisor.out",
            canary_log_dir=run008c_root / "canary",
            recovery_batch_size=10,
            inspect_args=(
                "--model",
                "google/gemini-3.7-flash",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp008,model-c,run008C-GEMINI,evaluation-awareness",
                "--metadata",
                "experiment_id=008-evaluation-awareness",
                "--metadata",
                "phase=evaluation_awareness_naturalistic_embedding",
                "--metadata",
                "run_id=run-008C-GEMINI",
                "--metadata",
                "model_role=model_c_gemini",
                "--metadata",
                "preregistration_sha=0aa5935f6830afe3e9f447ca9c299420e0a39586",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp008_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "008B-A-GPT": RunSpec(
            run_id="008B-A-GPT",
            experiment_id="008b-evaluation-awareness",
            title="Experiment 008B Run GPT-5.6 Sol",
            frozen_commit=exp008b_frozen_commit,
            scientific_paths=EXP008B_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp008b/"
                "inspect_task.py@exp008b_model_a_gpt56_sol"
            ),
            model="openai/gpt-5.6-sol",
            total_samples=120,
            condition_counts=exp008b_counts,
            log_dir=run008ba_root / "inspect",
            status_path=run008ba_root / "RUN_STATUS.json",
            operational_log=run008ba_root / "operational.log",
            lock_path=run008ba_root / "RUN_LOCK.json",
            pid_path=run008ba_root / "RUNNER.pid",
            stdout_path=run008ba_root / "runner-supervisor.out",
            canary_log_dir=run008ba_root / "canary",
            recovery_batch_size=10,
            inspect_args=(
                "--model",
                "openai/gpt-5.6-sol",
                "--max-tokens",
                "4096",
                "--reasoning-effort",
                "medium",
                "--verbosity",
                "medium",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp008b,model-a,run008B-A-GPT,evaluation-awareness-two-phase",
                "--metadata",
                "experiment_id=008b-evaluation-awareness",
                "--metadata",
                "phase=evaluation_awareness_naturalistic_embedding_two_phase",
                "--metadata",
                "run_id=run-008B-A-GPT",
                "--metadata",
                "model_role=model_a_gpt",
                "--metadata",
                "preregistration_sha=d0d249fd8eb6164a6dc2c4541c3496041b16e33d",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp008b_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "008B-B-CLAUDE": RunSpec(
            run_id="008B-B-CLAUDE",
            experiment_id="008b-evaluation-awareness",
            title="Experiment 008B Run Claude Sonnet 5",
            frozen_commit=exp008b_frozen_commit,
            scientific_paths=EXP008B_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp008b/"
                "inspect_task.py@exp008b_model_b_claude_sonnet5"
            ),
            model="anthropic/claude-sonnet-5",
            total_samples=120,
            condition_counts=exp008b_counts,
            log_dir=run008bb_root / "inspect",
            status_path=run008bb_root / "RUN_STATUS.json",
            operational_log=run008bb_root / "operational.log",
            lock_path=run008bb_root / "RUN_LOCK.json",
            pid_path=run008bb_root / "RUNNER.pid",
            stdout_path=run008bb_root / "runner-supervisor.out",
            canary_log_dir=run008bb_root / "canary",
            recovery_batch_size=10,
            inspect_args=(
                "--model",
                "anthropic/claude-sonnet-5",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp008b,model-b,run008B-B-CLAUDE,evaluation-awareness-two-phase",
                "--metadata",
                "experiment_id=008b-evaluation-awareness",
                "--metadata",
                "phase=evaluation_awareness_naturalistic_embedding_two_phase",
                "--metadata",
                "run_id=run-008B-B-CLAUDE",
                "--metadata",
                "model_role=model_b_claude",
                "--metadata",
                "preregistration_sha=d0d249fd8eb6164a6dc2c4541c3496041b16e33d",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp008b_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "008B-C-GEMINI": RunSpec(
            run_id="008B-C-GEMINI",
            experiment_id="008b-evaluation-awareness",
            title="Experiment 008B Run Gemini 3.7 Flash",
            frozen_commit=exp008b_frozen_commit,
            scientific_paths=EXP008B_SCIENTIFIC_FREEZE_PATHS,
            task=(
                "artificial_agency/experiments/exp008b/"
                "inspect_task.py@exp008b_model_c_gemini37_flash"
            ),
            model="google/gemini-3.7-flash",
            total_samples=120,
            condition_counts=exp008b_counts,
            log_dir=run008bc_root / "inspect",
            status_path=run008bc_root / "RUN_STATUS.json",
            operational_log=run008bc_root / "operational.log",
            lock_path=run008bc_root / "RUN_LOCK.json",
            pid_path=run008bc_root / "RUNNER.pid",
            stdout_path=run008bc_root / "runner-supervisor.out",
            canary_log_dir=run008bc_root / "canary",
            recovery_batch_size=10,
            inspect_args=(
                "--model",
                "google/gemini-3.7-flash",
                "--max-tokens",
                "4096",
                "--no-parallel-tool-calls",
                "--epochs",
                "1",
                "--max-connections",
                "1",
                "--log-format",
                "json",
                "--tags",
                "exp008b,model-c,run008B-C-GEMINI,evaluation-awareness-two-phase",
                "--metadata",
                "experiment_id=008b-evaluation-awareness",
                "--metadata",
                "phase=evaluation_awareness_naturalistic_embedding_two_phase",
                "--metadata",
                "run_id=run-008B-C-GEMINI",
                "--metadata",
                "model_role=model_c_gemini",
                "--metadata",
                "preregistration_sha=d0d249fd8eb6164a6dc2c4541c3496041b16e33d",
                "--metadata",
                "scenario_suite_v1_sha=3592be66883e2c1cd826abecbe92e90945099ea6",
                "--metadata",
                f"git_commit={exp008b_frozen_commit}",
                "--max-retries",
                "3",
                "--timeout",
                "60",
                "--attempt-timeout",
                "45",
                "--log-buffer",
                "1",
                "--checkpoint",
                "turn:1",
                "--display",
                "plain",
            ),
        ),
        "PERSISTENCE_DIAGNOSTIC": RunSpec(
            run_id="PERSISTENCE_DIAGNOSTIC",
            experiment_id="runner-persistence-diagnostic",
            title="Runner v2 Persistence Diagnostic",
            frozen_commit="6301fc0b78ded0200fd6203d4888ac2b3c33cae7",
            scientific_paths=(),
            task=PERSISTENCE_DIAGNOSTIC_TASK,
            model="none",
            total_samples=0,
            condition_counts={},
            log_dir=repo / "results" / "runner-diagnostics" / "persistence" / "logs",
            status_path=repo / "results" / "runner-diagnostics" / "persistence" / "RUN_STATUS.json",
            operational_log=repo / "results" / "runner-diagnostics" / "persistence" / "operational.log",
            lock_path=repo / "results" / "runner-diagnostics" / "persistence" / "RUN_LOCK.json",
            pid_path=repo / "results" / "runner-diagnostics" / "persistence" / "RUNNER.pid",
            stdout_path=repo / "results" / "runner-diagnostics" / "persistence" / "runner-supervisor.out",
            canary_log_dir=repo / "results" / "runner-diagnostics" / "persistence" / "canary",
        ),
    }
